name = "Burgers2D"
uuid = "a9521552-03c6-4607-b84d-f7a70d04f472"
keywords = ["julia", "PDE", "Burgers equation", "spectral methods"]
authors = ["Fabian Circelli and Navid C. Constantinou <navidcy@gmail.com>"]
description = "Tools for solving the 2D Burgers equation on a doubly-periodic two-dimensional domain."
repository = "https://github.com/FChaosi/Burgers2D.jl"
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
